# -*- mode: ruby -*-

brew 'aspell'
brew 'awscli'
brew 'bat'
brew 'bluetoothconnector'
brew 'clisp'
brew 'colordiff'
brew 'coreutils'
brew 'direnv'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'ghq'
brew 'git'
brew 'git-delta'
brew 'gopls'
brew 'htop'
brew 'hugo'
brew 'jq'
brew 'less'
brew 'mtr'
brew 'node'
brew 'noti'
brew 'nvm'
brew 'prettier'
brew 'rbenv'
brew 'ripgrep'
brew 'ruby-build'
brew 'sqlite'
brew 'switchaudio-osx'
brew 'tcping'
brew 'telnet'
brew 'terminal-notifier'
brew 'terraform-ls'
brew 'tfenv'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'typescript-language-server'
brew 'wget'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'appcleaner'
cask 'claude-code'
cask 'dash'
cask 'font-moralerspace'
cask 'gcloud-cli'
cask 'ghostty'
cask 'karabiner-elements'
cask 'keepingyouawake'
cask 'monitorcontrol'
cask 'session-manager-plugin'

tap 'd12frosted/emacs-plus'
# Prebuilt, and self-contained: it links no Homebrew dylibs, so a stray
# cleanup can no longer strip the libraries out from under it. Cannot
# coexist with an emacs-plus@N formula -- both own bin/emacs.
cask 'emacs-plus-app'

# Load local Brewfile if it exists (for machine-specific packages)
instance_eval(File.read(File.expand_path("./Brewfile.local"))) if File.exist?("Brewfile.local")
